# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nw5bt0LWhkvFQgCCPCWWXaXyhwHZ5LAH
"""

import cv2
from google.colab.patches import cv2_imshow

url = "https://get.wallhere.com/photo/cat-grass-kittens-whiskers-cats-kitten-fauna-cat-like-mammal-snout-small-to-medium-sized-cats-domestic-short-haired-cat-european-shorthair-domestic-long-haired-cat-norwegian-forest-cat-siberian-nebelung-ragdoll-munchkin-puss-british-semi-longhair-1600x1116-px-lovely-desktop-images-cat-images-cat-photos-cat-wallpapers-cutties-feline-pictures-on-the-wall-pussycats-ragamuffin-aegean-cat-asian-semi-longhair-802993.jpg"
!wget {url} -O original_image.jpg
original_image = cv2.imread("original_image.jpg")
gray_image = cv2.cvtColor(original_image, cv2.COLOR_BGR2GRAY)
cv2.imwrite("gray_image.jpg", gray_image)
print("Asl rasm:")
cv2_imshow(original_image)
print("Oq-qora rasm:")
cv2_imshow(gray_image)